#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------

if [ ! -f /firstrun.txt ]
then
    touch /firstrun.txt
    useradd -u $UID MC
    echo "$USER" >> /USER.txt
    echo "$PASS" >> /PASS.txt
fi

if [ ! -f /data/minecraft_server.jar ]
then
    sudo -u MC curl "https://s3.amazonaws.com/Minecraft.Download/versions/1.10/minecraft_server.1.10.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/rtoolkit.sh ]
then
    sudo -u MC cp -rn /mcrtoolkit/* /data
    chmod +x /data/rtoolkit.sh
fi

cd /data/
sudo -u MC ./rtoolkit.sh

